GET http://localhost:3004/todos/
###

//Scenario 1
GET http://localhost:3004/todos/?status=TO%20DO
### 

//Scenario 2 
GET http://localhost:3004/todos/?priority=HIGH 
### 

//Scenario 3 
GET http://localhost:3004/todos/?priority=HIGH&status=IN%20PROGRESS 
### 

//Scenario 4 
GET http://localhost:3004/todos/?search_q=Event 
###

GET http://localhost:3004/todos/10/
###

POST http://localhost:3004/todos/
Content-Type: application/json 

{
  "id": 10,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}

### 
PUT http://localhost:3004/todos/10/
Content-Type: application/json 

{ "status": "DONE" }

###
PUT http://localhost:3004/todos/10/
Content-Type: application/json 

{ "priority": "HIGH" }
### 


PUT http://localhost:3004/todos/10/
Content-Type: application/json 

{ "todo": "Great Match" }


###
DELETE http://localhost:3004/todos/10/ 

